### ISSUE TITLE
RubyGems version error: invalid gem version when Gemfile.lock produced by bundler 2.2.0 or newer

### ISSUE THREAD

**Issue by nicbet** [aquasecurity/go-gem-version#1]
Bundler introduced platform specific Gem resolutions with version 2.2.0 in December 2020, adding platform suffixes to platform-specific gem resolutions like `nokogiri`.

Example `Gemfile.lock`:

```
GEM
  remote: https://rubygems.org/
  specs:
    nokogiri (1.13.1)
      mini_portile2 (~> 2.7.0)
      racc (~> 1.4)
    nokogiri (1.13.1-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.13.1-x86_64-linux)
      racc (~> 1.4)

PLATFORMS
  ruby
  x86_64-darwin-19
  x86_64-linux-musl

RUBY VERSION
   ruby 2.7.5p203

BUNDLED WITH
   2.2.32
```

Trivy fails parsing these newer format `Gemfile.lock`files, as `gem.NewVersion` cannot properly parse the platform suffix.

```go
// File trivy/pkg/detector/library/compare/rubygems/compare.go:21
v, err := gem.NewVersion(currentVersion)
	if err != nil {
		return false, xerrors.Errorf("RubyGems version error (%s): %s", currentVersion, err)
	}
```

As a result, Trivy scans of newer format `Gemfile.lock` files produce many lines of output warnings during CI, and may not perform vulnerability checks against gems with platform suffixes.

**Comment by knqyf263** [comment]
Thanks for filing an issue. Capturing versions didn't work well, while `go-gem-version` works correctly. It was fixed.
